WebApp/Controllers/ChannelsController.cs
using App.BLL.DTO;
using App.Contracts.BLL;
using App.Contracts.DAL;
using App.Domain.Enums;
using App.Domain.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    [Route("/Channels/{id?}/{action=Index}")]
    public class ChannelsController : Controller
    {
        private readonly IAppBll _bll;
        private readonly UserManager<AppUser> _userManager;

        private Guid UserId => Guid.Parse(_userManager.GetUserId(User)!);

        public ChannelsController(IAppBll bll, UserManager<AppUser> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }

        // GET: Admin/Channels
        public async Task<IActionResult> Index(Guid? id)
        {
            var vm = new ChannelLayoutViewModel
            {
                Channels = (await _bll.Channels.GetAllAsync(UserId)).OrderBy(c => c.Type)
            };

            if (id != null)
            {
                vm.ActiveChannel = vm.Channels.FirstOrDefault(c => c.Id == id.Value);
                vm.ReceivedMessages = await _bll.Recipients.GetAllByChannelAsync(id.Value, UserId);

                foreach (var r in vm.ReceivedMessages)
                {
                    if (r.IsRead) continue;

                    var rec = new Recipient
                    {
                        IsRead = true,
                        Id = r.Id,
                        MemberId = r.MemberId,
                        MessageHeaderId = r.MessageHeaderId
                    };
                    
                    _bll.Recipients.Update(rec);
                }

                await _bll.SaveChangesAsync();
            }

            return View(vm);
        }

        // GET: Admin/Channels/Create
        [Route("/Channels/Create")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Channels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("/Channels/Create")]
        public async Task<IActionResult> Create(Channel c)
        {
            if (ModelState.IsValid)
            {
                c.Type = EChannelType.Group;
                c.OwnerId = UserId;
                
                var res = _bll.Channels.Add(c);

                var member = new ChannelMember
                {
                    ChannelId = res.Id,
                    AppUserId = UserId
                };

                _bll.ChannelMembers.Add(member);
                
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new {id = res.Id});
            }
            
            return View(c);
        }

        // GET: Admin/Channels/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _bll.Channels.FirstOrDefaultAsync(id.Value);
            if (channel == null)
            {
                return NotFound();
            }
            
            return View(channel);
        }

        // POST: Admin/Channels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Channel c)
        {
            if (id != c.Id)
            {
                return NotFound();
            }

            var channel = await _bll.Channels.FirstOrDefaultAsync(id);
            
            if (channel!.OwnerId != UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    channel.Name = c.Name;
                    channel.Description = c.Description;
                    
                    _bll.Channels.Update(channel);
                    await _bll.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _bll.Channels.ExistsAsync(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            return View(c);
        }

        // GET: Admin/Channels/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _bll.Channels.FirstOrDefaultAsync(id.Value, UserId);
            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // POST: Admin/Channels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _bll.Channels.RemoveAsync(id, UserId);

            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Controllers/MatchesController.cs
using App.BLL.DTO;
using App.BLL.DTO.Identity;
using App.Contracts.BLL;
using App.Contracts.DAL;
using App.Domain.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.ViewModels;
using Channel = App.Domain.Channel;
using Route = App.Domain.Route;

namespace WebApp.Controllers
{
    [Authorize]
    public class MatchesController : Controller
    {
        private readonly IAppBll _bll;
        private readonly UserManager<App.Domain.Identity.AppUser> _userManager;
        
        private Guid UserId => Guid.Parse(_userManager.GetUserId(User)!);

        public MatchesController(IAppBll bll, UserManager<App.Domain.Identity.AppUser> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }


        // GET: Admin/Matches
        public async Task<IActionResult> Index()
        {
            var res = await _bll.Matches.GetAllVisibleAsync(UserId);
            return View(res);
        }

        [HttpPost]
        public async Task<IActionResult> Accept(Guid? id)
        {
            if (id == null)
            {
                return View(nameof(Index));
            }

            var match = await _bll.Matches.Accept(id.Value, Guid.Parse(_userManager.GetUserId(User)!));

            if (match.Accepted)
            {
                var channel = await _bll.Channels.DmExistsBetweenUsers(
                    match.Route1!.AppUserId, match.Route2!.AppUserId);

                if (channel == null)
                {
                    channel = _bll.Channels.Add(new App.BLL.DTO.Channel()
                    {
                        Type = EChannelType.Direct
                    });

                    _bll.ChannelMembers.Add(new ChannelMember()
                    {
                        ChannelId = channel.Id,
                        AppUserId = match.Route1!.AppUserId
                    });
                    
                    _bll.ChannelMembers.Add(new ChannelMember()
                    {
                        ChannelId = channel.Id,
                        AppUserId = match.Route2!.AppUserId
                    });
                    
                }
                
                await _bll.SaveChangesAsync();
                
                return RedirectToAction("Details", nameof(Channel) + "s", new {id = channel.Id});
            }

            await _bll.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Controllers/MessagesController.cs
using App.Contracts.BLL;
using App.Contracts.DAL;
using App.BLL.DTO;
using App.Domain.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.ViewModels;
using Channel = App.BLL.DTO.Channel;

namespace WebApp.Controllers
{
    [Authorize]
    [Route("/Channels/{channelId}/Messages/[action]/{id?}")]
    public class MessagesController : Controller
    {
        private readonly IAppBll _bll;
        private readonly UserManager<AppUser> _userManager;

        private Guid UserId => Guid.Parse(_userManager.GetUserId(User)!);

        public MessagesController(IAppBll bll, UserManager<AppUser> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }

        // POST: Messages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid channelId, string content, Guid? parentId = null)
        {
            // TODO: Check if user in channel
            
            var channel = await _bll.Channels.FirstOrDefaultAsync(channelId, UserId);
            
            var header = new MessageHeader
            {
                ChannelId = channelId,
                ParentId = parentId,
                SenderId = channel!.Members!.FirstOrDefault(m => m.AppUserId == UserId)!.Id,
                SentAt = DateTime.UtcNow
            };

            header = _bll.MessageHeaders.Add(header);

            var message = new Message
            {
                HeaderId = header.Id,
                Content = content
            };

            _bll.Messages.Add(message);

            foreach (var cm in channel.Members!)
            {
                var recipient = new Recipient
                {
                    MemberId = cm.Id,
                    MessageHeaderId = header.Id,
                    IsRead = cm.AppUserId == UserId
                };
                _bll.Recipients.Add(recipient);
            }

            await _bll.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index), nameof(Channel) + "s", new { id = channelId });
        }
        
        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid channelId, Guid id)
        {
            var channel = await _bll.Channels.FirstOrDefaultAsync(channelId);

            if (channel != null && channel.OwnerId == UserId)
            {
                var recipient = await _bll.Recipients.FirstOrDefaultAsync(id, UserId);
                
                await _bll.MessageHeaders.RemoveAsync(recipient!.MessageHeader!.Id);
            
                await _bll.SaveChangesAsync();
            }
            
            return RedirectToAction(nameof(Index), nameof(Channel) + "s", new { id = channelId });
        }
    }
}

WebApp/Controllers/RoutesController.cs
using App.Contracts.BLL;
using App.Contracts.DAL;
using App.Domain;
using App.Domain.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    public class RoutesController : Controller
    {
        private readonly IAppBll _bll;
        private readonly UserManager<AppUser> _userManager;

        private Guid UserId => Guid.Parse(_userManager.GetUserId(User)!);

        public RoutesController(IAppBll bll, UserManager<AppUser> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }

        // GET: Admin/Routes
        public async Task<IActionResult> Index()
        {
            var res = await _bll.Routes.GetAllAsync(UserId);
            return View(res);
        }

        // GET: Admin/Routes/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || !IsRouteOwnedByUser(id.Value))
            {
                return NotFound();
            }

            var route = await _bll.Routes.FirstOrDefaultAsync(id.Value);
            if (route == null)
            {
                return NotFound();
            }

            return View(route);
        }

        // GET: Admin/Routes/Create
        public IActionResult Create()
        {
            return View(new App.BLL.DTO.Route());
        }

        // POST: Admin/Routes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(App.BLL.DTO.Route r)
        {
            if (ModelState.IsValid)
            {
                _bll.Routes.AddToUser(UserId, r);

                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(r);
        }

        // GET: Admin/Routes/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || !IsRouteOwnedByUser(id.Value))
            {
                return NotFound();
            }

            var route = await _bll.Routes.FirstOrDefaultAsync(id.Value);
            if (route == null)
            {
                return NotFound();
            }
            
            return View(route);
        }

        // POST: Admin/Routes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, App.BLL.DTO.Route r)
        {
            if (id != r.Id || !IsRouteOwnedByUser(id))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _bll.Routes.UpdateForUser(UserId, r);

                    r.Locations = (await _bll.Locations.GetAllByRouteIdAsync(r.Id)).ToList();
                    
                    await RecalculateMatches(UserId, r);
                    
                    await _bll.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _bll.Routes.ExistsAsync(r.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(r);
        }

        private async Task RecalculateMatches(Guid userId, App.BLL.DTO.Route route)
        {
            await _bll.Matches.DeleteAllByRouteAsync(route.Id);

            foreach (var r in await _bll.Routes.GetAllNotOwnedByUserAsync(userId))
            {
                var match = _bll.Matches.CalculateMatch(route, r);
                if (match.MatchPercent > .8) _bll.Matches.Add(match);
            }
        }

        // GET: Admin/Routes/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || !IsRouteOwnedByUser(id.Value))
            {
                return NotFound();
            }

            var route = await _bll.Routes.FirstOrDefaultAsync(id.Value);
            if (route == null)
            {
                return NotFound();
            }

            return View(route);
        }

        // POST: Admin/Routes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (!IsRouteOwnedByUser(id))
            {
                return NotFound();
            }
            
            await _bll.Routes.RemoveAsync(id);

            await _bll.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        private bool IsRouteOwnedByUser(Guid routeId)
        {
            return _bll.Routes.IsRouteOwnedByUser(routeId, UserId);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SyncRide</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SyncRide</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">@Base.Resources.Views.Shared._Layout.Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">@Base.Resources.Views.Shared._Layout.Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Matches" asp-action="Index">@App.Resources.Domain.RMatch.Matches</a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
                <partial name="_languageSelectionPartial"/>
                <partial name="_adminDropdownPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - SyncRide - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Base.Resources.Views.Shared._Layout.Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_adminDropdownPartial.cshtml
@if (User.IsInRole("Admin"))
{
    <ul class="navbar-nav ms-2">
        <li class="dropdown">
            <button class="btn btn-dark dropdown-toggle" type="button" id="admControllers" data-bs-toggle="dropdown" aria-expanded="false">
                @Base.Resources.Views.Shared._Layout.AdminControllers
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" asp-area="Admin" asp-controller="ChannelMembers" asp-action="Index">@App.Resources.Domain.RChannelMember.ChannelMembers</a></li>
                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Channels" asp-action="Index">@App.Resources.Domain.RChannel.Channels</a></li>
                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Locations" asp-action="Index">@App.Resources.Domain.RLocation.Locations</a></li>
                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Matches" asp-action="Index">@App.Resources.Domain.RMatch.Matches</a></li>
                <li><a class="dropdown-item" asp-area="Admin" asp-controller="MessageHeaders" asp-action="Index">@App.Resources.Domain.RMessageHeader.MessageHeaders</a></li>
                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Messages" asp-action="Index">@App.Resources.Domain.RMessage.Messages</a></li>
                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Recipients" asp-action="Index">@App.Resources.Domain.RRecipient.Recipients</a></li>
                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Routes" asp-action="Index">@App.Resources.Domain.RRoute.Routes</a></li>
                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Index">@Base.Resources.Domain.Identity.RAppUser.AppUsers</a></li>
            </ul>
        </li>
    </ul>
}

WebApp/Views/Shared/_languageSelectionPartial.cshtml
@using Microsoft.Extensions.Options
@inject IOptions<RequestLocalizationOptions> LocalizationOptions;
@{
    var cultureItems = LocalizationOptions.Value.SupportedCultures!.Select(c => new
    {
        Value = c.Name,
        Text = c.NativeName
    });
}
<ul class="navbar-nav">
    <li class="dropstart">
    <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        @Thread.CurrentThread.CurrentCulture.Name
    </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            @foreach (var item in cultureItems)
            {
                <li>
                    <a class="dropdown-item"
                       asp-area=""
                       asp-controller="Home"
                       asp-action="SetLanguage"
                       asp-route-culture="@item.Value"
                       asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString">
                        @item.Text
                    </a>
                </li>
                
            }
        </ul>
    </li>
</ul>