WebApp/Areas/Admin/Controllers/ChannelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using App.Contracts.DAL;
using App.Contracts.DAL.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.DAL.EF;
using App.DAL.EF.Repositories;
using App.Domain;
using App.Domain.Identity;
using Microsoft.AspNetCore.Authorization;
using WebApp.Areas.Admin.ViewModels;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ChannelsController : Controller
    {
        private readonly IAppUnitOfWork _uow;

        public ChannelsController(IAppUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Admin/Channels
        public async Task<IActionResult> Index()
        {
            var res = await _uow.Channels.GetAllAsync();
            return View(res);
        }

        // GET: Admin/Channels/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _uow.Channels.FirstOrDefaultAsync(id.Value);
            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // GET: Admin/Channels/Create
        public async Task<IActionResult> Create()
        {
            var vm = new ChannelCreateEditViewModel
            {
                AppUserSelectList = new SelectList(await _uow.Users.GetAllAsync(), nameof(AppUser.Id), nameof(AppUser.Email))
            };
            return View(vm);
        }

        // POST: Admin/Channels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ChannelCreateEditViewModel vm)
        {
            if (ModelState.IsValid)
            {
                _uow.Channels.Add(vm.Channel);
                await _uow.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            vm.AppUserSelectList = new SelectList(await _uow.Users.GetAllAsync(), nameof(AppUser.Id), nameof(AppUser.Email), vm.Channel.OwnerId);
            
            return View(vm);
        }

        // GET: Admin/Channels/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _uow.Channels.FirstOrDefaultAsync(id.Value);
            if (channel == null)
            {
                return NotFound();
            }

            var vm = new ChannelCreateEditViewModel
            {
                Channel = channel,
                AppUserSelectList = 
                    new SelectList(await _uow.Users.GetAllAsync(), nameof(AppUser.Id), nameof(AppUser.Email), channel.OwnerId)
            };
            
            return View(vm);
        }

        // POST: Admin/Channels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ChannelCreateEditViewModel vm)
        {
            if (id != vm.Channel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _uow.Channels.Update(vm.Channel);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _uow.Channels.ExistsAsync(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            vm.AppUserSelectList = new SelectList(await _uow.Users.GetAllAsync(), nameof(AppUser.Id),
                nameof(AppUser.Email), vm.Channel.OwnerId);
            
            return View(vm);
        }

        // GET: Admin/Channels/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _uow.Channels.FirstOrDefaultAsync(id.Value);
            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // POST: Admin/Channels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _uow.Channels.RemoveAsync(id);

            await _uow.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Controllers/ChannelMembersController.cs
using App.BLL.DTO;
using App.Contracts.BLL;
using App.Contracts.DAL;
using App.Domain.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.ViewModels;
using Channel = App.Domain.Channel;
using Route = App.Domain.Route;

namespace WebApp.Controllers
{
    [Route("/Channels/{channelId}/Members/[action]/{id?}")]
    public class ChannelMembersController : Controller
    {
        private readonly IAppBll _bll;
        private readonly UserManager<AppUser> _userManager;

        private Guid UserId => Guid.Parse(_userManager.GetUserId(User)!);

        public ChannelMembersController(IAppBll bll, UserManager<AppUser> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }

        // GET: Admin/ChannelMembers/Create
        public async Task<IActionResult> Create()
        {
            var vm = new ChannelMemberCreateEditViewModel
            {
                MemberSelectList = new SelectList(
                    await _bll.Users.GetAllMatchedUsersAsync(UserId), 
                    nameof(App.DAL.DTO.Identity.AppUser.Id), 
                    nameof(App.BLL.DTO.Identity.AppUser.FullName)
                    )
            };
            return View(vm);
        }

        // POST: Admin/ChannelMembers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid channelId, ChannelMemberCreateEditViewModel vm)
        {
            if (!await _bll.Channels.ExistsAsync(channelId, UserId)) 
                return RedirectToAction(nameof(Index), nameof(Channel) + "s", new {id = channelId});
            
            if (ModelState.IsValid)
            {
                var member = new ChannelMember
                {
                    AppUserId = vm.AppUserId,
                    ChannelId = channelId
                };
                
                _bll.ChannelMembers.Add(member);
                await _bll.SaveChangesAsync();
                return RedirectToAction(nameof(Index), nameof(Channel) + "s", new {id = channelId});
            }

            vm.MemberSelectList = new SelectList(
                await _bll.Users.GetAllMatchedUsersAsync(UserId),
                nameof(App.DAL.DTO.Identity.AppUser.Id),
                nameof(App.BLL.DTO.Identity.AppUser.FullName)
            );

            return View(vm);
        }

        // GET: Admin/ChannelMembers/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channelMember = await _bll.ChannelMembers.FirstOrDefaultAsync(id.Value);
            if (channelMember == null || channelMember.Channel!.OwnerId != UserId)
            {
                return NotFound();
            }

            var vm = new ChannelMemberCreateEditViewModel
            {
                IsOwner = channelMember.AppUserId == channelMember.Channel.OwnerId,
                Id = channelMember.Id,
                AppUserId = channelMember.AppUserId,
                Nickname = channelMember.Nickname
            };
            
            return View(vm);
        }

        // POST: Admin/ChannelMembers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid channelId, Guid id, ChannelMemberCreateEditViewModel vm)
        {
            if (id != vm.Id)
            {
                return NotFound();
            }

            var member = await _bll.ChannelMembers.FirstOrDefaultAsync(id);
            
            if (member!.Channel!.OwnerId != UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    member.Nickname = vm.Nickname;
                    
                    _bll.ChannelMembers.Update(member);
                    await _bll.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _bll.ChannelMembers.ExistsAsync(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), nameof(Channel) + "s", new {id = channelId});
            }
            
            return View(vm);
        }
        
        public async Task<IActionResult> Kick(Guid channelId, Guid id, ChannelMemberCreateEditViewModel vm)
        {
            if (id != vm.Id)
            {
                return NotFound();
            }
            
            var member = await _bll.ChannelMembers.FirstOrDefaultAsync(id);
            if (member!.Channel!.OwnerId == UserId)
            {
                await _bll.ChannelMembers.RemoveAsync(member);
                await _bll.SaveChangesAsync();
            }
            
            return RedirectToAction(nameof(Index), nameof(Channel) + "s", new {id = channelId});
        }

        public async Task<IActionResult> MakeOwner(Guid channelId, Guid id, ChannelMemberCreateEditViewModel vm)
        {
            if (id != vm.Id)
            {
                return NotFound();
            }
            
            var channel = await _bll.Channels.FirstOrDefaultAsync(channelId);
            
            if (channel != null && channel.OwnerId == UserId)
            {
                channel.OwnerId = vm.AppUserId;
                channel.Owner = null; // SHOULD CREATE NEW OBJECT!
                
                _bll.Channels.Update(channel);
                await _bll.SaveChangesAsync();
            }
            
            return RedirectToAction(nameof(Index), nameof(Channel) + "s", new {id = channelId});
        }
    }
}

WebApp/Controllers/MessagesController.cs
using App.Contracts.BLL;
using App.Contracts.DAL;
using App.BLL.DTO;
using App.Domain.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.ViewModels;
using Channel = App.BLL.DTO.Channel;

namespace WebApp.Controllers
{
    [Authorize]
    [Route("/Channels/{channelId}/Messages/[action]/{id?}")]
    public class MessagesController : Controller
    {
        private readonly IAppBll _bll;
        private readonly UserManager<AppUser> _userManager;

        private Guid UserId => Guid.Parse(_userManager.GetUserId(User)!);

        public MessagesController(IAppBll bll, UserManager<AppUser> userManager)
        {
            _bll = bll;
            _userManager = userManager;
        }

        // POST: Messages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid channelId, string content, Guid? parentId = null)
        {
            // TODO: Check if user in channel
            
            var channel = await _bll.Channels.FirstOrDefaultAsync(channelId, UserId);
            
            var header = new MessageHeader
            {
                ChannelId = channelId,
                ParentId = parentId,
                SenderId = channel!.Members!.FirstOrDefault(m => m.AppUserId == UserId)!.Id,
                SentAt = DateTime.UtcNow
            };

            header = _bll.MessageHeaders.Add(header);

            var message = new Message
            {
                HeaderId = header.Id,
                Content = content
            };

            _bll.Messages.Add(message);

            foreach (var cm in channel.Members!)
            {
                var recipient = new Recipient
                {
                    MemberId = cm.Id,
                    MessageHeaderId = header.Id,
                    IsRead = cm.AppUserId == UserId
                };
                _bll.Recipients.Add(recipient);
            }

            await _bll.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index), nameof(Channel) + "s", new { id = channelId });
        }
        
        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid channelId, Guid id)
        {
            var channel = await _bll.Channels.FirstOrDefaultAsync(channelId);

            if (channel != null && channel.OwnerId == UserId)
            {
                var recipient = await _bll.Recipients.FirstOrDefaultAsync(id, UserId);
                
                await _bll.MessageHeaders.RemoveAsync(recipient!.MessageHeader!.Id);
            
                await _bll.SaveChangesAsync();
            }
            
            return RedirectToAction(nameof(Index), nameof(Channel) + "s", new { id = channelId });
        }
    }
}

WebApp/Views/Channels/Create.cshtml
@using App.Domain.Enums
@model App.BLL.DTO.Channel

@{
    ViewData["Title"] = "Create";
}

<h1>@Base.Resources.Domain._Shared.Create</h1>

<h4>@App.Resources.Domain.RChannel.Channel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            
            <partial name="_CreateEdit" model="Model"/>
            
            <div class="form-group">
                <input type="submit" value="@Base.Resources.Domain._Shared.Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Base.Resources.Domain._Shared.BackToList</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Channels/Delete.cshtml
@model App.BLL.DTO.Channel

@{
    ViewData["Title"] = "Delete";
}

<h1>@Base.Resources.Domain._Shared.Delete</h1>

<h1>@Base.Resources.Domain._Shared.AreYouSure</h1>
<div>
    <h4>@App.Resources.Domain.RChannel.Channel</h4>
    <hr />
    
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="@Base.Resources.Domain._Shared.Delete" class="btn btn-danger" /> |
        <a asp-action="Index">@Base.Resources.Domain._Shared.BackToList</a>
    </form>
</div>

WebApp/Views/Channels/Edit.cshtml
@using App.Domain.Enums
@model App.BLL.DTO.Channel

@{
    ViewData["Title"] = "Edit";
}

<h1>@Base.Resources.Domain._Shared.Edit</h1>

<h4>@App.Resources.Domain.RChannel.Channel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id" />
            
            <partial name="_CreateEdit" model="Model"/>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Base.Resources.Domain._Shared.BackToList</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Channels/Index.cshtml
@model ChannelLayoutViewModel

<div class="row">
    <div class="col-2">
        <partial name="_channels" model="Model"/>
    </div>
    <div class="col">
        <partial name="_chat" model="Model"/>
    </div>
    <div class="col-2">
        <partial name="_members" model="Model"/>
    </div>
</div>

@section Scripts
{
    <script>
        let m = document.querySelector("#messages");
        m.scrollTop = m.scrollHeight;
    </script>
}

WebApp/Views/Channels/_CreateEdit.cshtml
@model App.BLL.DTO.Channel

<div asp-validation-summary="All" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Name" class="control-label">@App.Resources.Domain.RChannel.Name</label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Description" class="control-label">@App.Resources.Domain.RChannel.Description</label>
    <input asp-for="Description" class="form-control" />
    <span asp-validation-for="Description" class="text-danger"></span>
</div>

WebApp/Views/Channels/_channels.cshtml
@model ChannelLayoutViewModel

@if (!Model.Channels.Any())
{
    return;
}

<ul class="overflow-auto nav nav-underline flex-column h-100">
    <li>
        <a asp-action="Create" class="btn btn-outline-success mb-2 w-100">Create Group</a>
    </li>
    @foreach (var c in Model.Channels)
    {
        <li class="nav-item mb-2 border-bottom">
            <a asp-area="" asp-action="Index" asp-route-id="@c.Id"
               class="nav-link @(c.Id == Model.ActiveChannel?.Id ? "active" : "")">
                @c.ChannelName
            </a>
        </li>
    }
</ul>

WebApp/Views/Channels/_chat.cshtml
@using App.Domain.Enums
@using App.Domain.Identity
@using Microsoft.AspNetCore.Identity
@model ChannelLayoutViewModel
@inject UserManager<AppUser> UserManager

@{
    var notReadlineRendered = false;
    
    string CombineIconPath(App.BLL.DTO.Identity.AppUser user)
    {
        return "/Assets/Icons/" +
               (user.ProfilePictureExtension != null
                   ? user.Id + user.ProfilePictureExtension
                   : "default.png");
    }
}

@if (Model.ActiveChannel == null)
{
    <div class="text-center">
        <h1 class="display-4">Welcome To SyncRide</h1>
        <p>To get started create a route and wait for a match!</p>
    </div>
}
else
{
    var isOwner = Model.ActiveChannel.OwnerId == Guid.Parse(UserManager.GetUserId(User)!);
    
    <div class="row border-bottom box-shadow mb-3">
        <div class="col">
            <h2>@Model.ActiveChannel.ChannelName</h2>
            @Model.ActiveChannel.Description
        </div>
        @if (Model.ActiveChannel.Type == EChannelType.Group && isOwner)
        {
            <div class="col-md-auto">
                <a asp-action="Edit" asp-route-id="@Model.ActiveChannel.Id" class="btn btn-outline-info">@Base.Resources.Domain._Shared.Edit</a>
                <a asp-action="Delete" asp-route-id="@Model.ActiveChannel.Id" class="btn btn-outline-danger">@Base.Resources.Domain._Shared.Delete</a>
            </div>
        }
    </div>
    <div id="messages" class="d-flex flex-column pt-3">
        @foreach (var m in Model.ReceivedMessages!)
        {
            if (!notReadlineRendered && !m.IsRead)
            {
                <div class="row">
                    <div class="col">
                        <hr class="bg-danger w-100"/>
                    </div>
                    <div class="col-md-auto">
                        <span class="text-center text-danger">Not read</span>
                    </div>
                    <div class="col">
                        <hr class="bg-danger w-100"/>
                    </div>
                </div>
                
                notReadlineRendered = true;
            }
            <div id="m_@m.Id" class="row pb-3">
                <div class="col-md-auto">
                    <img alt="@m.MessageHeader!.Sender!.Name icon" src="@CombineIconPath(m.MessageHeader!.Sender!.AppUser!)" width="40" height="40" class="rounded-circle mt-2">
                </div>
                <div class="col">
                    @if (m.MessageHeader!.ParentId != null)
                    {
                        <div class="row fs-6">> @m.MessageHeader!.Parent!.Content</div>
                    }
                    <div class="row">
                        <span class="col-md-auto fs-5 fw-bold">@m.MessageHeader!.Sender!.Name</span> 
                        <span class="col text-muted mt-1 p-0">@m.MessageHeader!.SentAt</span>
                        @if (isOwner)
                        {
                            <form class="col-md-auto" asp-controller="Messages" asp-action="Delete" asp-route-id="@m.Id" asp-route-channelId="@Context.Request.RouteValues["id"]">
                                <button type="submit" value="delete" class="btn btn-link text-danger">Delete</button>
                            </form>
                        }
                    </div>
                    <div class="row fs-6">
                        <span>@m.MessageHeader?.Message?.Content</span>
                    </div>
                </div>
            </div>
        }
    </div>
    <div>
        <form asp-controller="Messages" asp-action="Create" asp-route-channelId="@Context.Request.RouteValues["id"]" class="row">
            <div class="col">
                <input class="form-control" name="content" placeholder="Send a message...">
            </div>
            <div class="col-md-auto">
                <button type="submit" value="Send" class="btn btn-outline-success">Send</button>
            </div>
        </form>
    </div>
}

WebApp/Views/Channels/_members.cshtml
@using App.Domain.Enums
@using App.Domain.Identity
@using Microsoft.AspNetCore.Identity
@model ChannelLayoutViewModel
@inject UserManager<AppUser> UserManager
@{
    string CombineIconPath(App.BLL.DTO.Identity.AppUser user)
    {
        return "/Assets/Icons/" +
               (user.ProfilePictureExtension != null
                   ? user.Id + user.ProfilePictureExtension
                   : "default.png");
    }
}


@if (Model.ActiveChannel == null)
{
    return;
}
<ul class="overflow-auto list-group">
    @{ var isOwner = Model.ActiveChannel.OwnerId == Guid.Parse(UserManager.GetUserId(User)!); }
    @if (Model.ActiveChannel.Type == EChannelType.Group && isOwner)
    {
        <li>
            <a asp-controller="ChannelMembers" asp-action="Create" asp-route-channelId="@Model.ActiveChannel.Id" class="btn btn-outline-success w-100 mb-2">Add a member</a>
        </li>
    }
    @if (Model.ActiveChannel.Members!.Count == 0)
    {
        <li>Strangely... now one is here?</li>
    }
    else
    {
        foreach (var cm in Model.ActiveChannel.Members)
        {
            <li class="list-group-item">
                <div class="row">
                    <div class="col-md-auto">
                        <img alt="@cm.Name icon" src="@CombineIconPath(cm.AppUser!)" width="40" height="40" class="@(
                            Model.ActiveChannel.OwnerId == cm.AppUserId ? "border border-2 border-warning" : ""
                        ) rounded-circle mt-1">
                    </div>
                    <div class="col">
                        <span class="d-inline-block">@cm.Name</span>
                        @if (isOwner)
                        {
                            <a asp-controller="ChannelMembers" asp-action="Edit" asp-route-channelId="@cm.ChannelId" asp-route-id="@cm.Id">@Base.Resources.Domain._Shared.Edit</a>
                            <span> | </span>
                        }
                        <a asp-area="Identity" asp-page="/Account/Index" asp-route-id="@cm.AppUserId" asp-route-channelId="@cm.ChannelId">@App.Resources.Domain.RMatch.ViewProfile</a>
                    </div>
                </div>
            </li>
        }
    }
</ul>